[project]
name = "app"
version = "0.1.0"
description = "A modular FastAPI backend"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "pandas",
]

[tool.uv.build-backend]
module-name = "app"
module-root = ""