[project]
name = "backend"
version = "0.1.0"
description = "A modular FastAPI backend"
dependencies = [
    "fastapi",
    "uvicorn",
    "pandas",
]
requires-python = ">=3.9"

[tool.uv]
python = "3.11"